config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  namespace :users do
    get 'admins', to: 'admins#index'
  end
  resources :music_lists, only: [:index, :show]
  resources :tags, only: [:show], param: :name
  resources :setlists, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/live.rb
class Live < ApplicationRecord
  has_many :setlists
end

app/models/medium.rb
class Medium < ApplicationRecord
  enum content_type: { youtube: "youtube" }

  has_many :medium_tags
  has_many :tags, through: :medium_tags
  has_one :youtube
end

app/models/medium_tag.rb
class MediumTag < ApplicationRecord
  belongs_to :medium
  belongs_to :tag
end

app/models/music_list.rb
class MusicList < ApplicationRecord
  has_many :music_list_youtubes
  has_many :youtubes, through: :music_list_youtubes
end

app/models/music_list_youtube.rb
class MusicListYoutube < ApplicationRecord
  belongs_to :music_list
  belongs_to :youtube
end

app/models/setlist.rb
class Setlist < ApplicationRecord
  belongs_to :live
  has_many :setlist_details
end

app/models/setlist_detail.rb
class SetlistDetail < ApplicationRecord
  belongs_to :setlist
  belongs_to :music_list
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :medium_tags
  has_many :media, through: :medium_tags

  # link_to で実行されるのを:idじゃなくて:nameに変更
  # ref: http://totech.hateblo.jp/entry/2015/12/19/205018
  def to_param
    name
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         # :registerable,
         # :recoverable, :rememberable, 
         :trackable
         # :validatable
  enum role: { admin: "admin", user: "user" }
end

app/models/youtube.rb
class Youtube < ApplicationRecord
  has_many :music_list_youtubes
  has_many :music_lists, through: :music_list_youtubes
  belongs_to :medium

  before_validation :create_medium

  def create_medium
    self.medium = self.medium.present? ? self.medium : ::Medium.new
    self.medium.content_type = "youtube"
    self.medium.published_at = published_at
  end

  def playtime
    m = duration.match(/PT(\d+)M(\d+)S/)
    "#{m[1]}分#{m[2]}秒"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def authenticate_admin!
    if user_signed_in? && current_user.admin?
      true
    else
      redirect_to root_path
    end
  end
end

app/controllers/lives_controller.rb
class LivesController < ApplicationController
  def index
    @lives = Live.all
  end

  def show
    @live = Live.find(params[:id])
  end
end

app/controllers/music_lists_controller.rb
class MusicListsController < ApplicationController
  def index
    @music_lists = MusicList.all
  end

  def show
    @music = MusicList.find(params[:id])
  end
end

app/controllers/setlists_controller.rb
class SetlistsController < ApplicationController
  before_action :set_setlist, only: [:show]

  def index
    @setlists = Setlist.all.group_by{|s| s.event_date.to_date}
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setlist
      @setlist = Setlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def setlist_params
    #   params.require(:setlist).permit(:index, :show)
    # end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find_by!(name: params[:name])
    @media = @tag.media.order(published_at: :desc)
  end
end

app/controllers/users/admins_controller.rb
class Users::AdminsController < ApplicationController
  before_action :authenticate_admin!

  def index
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  def after_sign_in_path_for(resource)
    if resource.is_a?(User) && resource.admin?
      users_admins_path
    else
      root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to setlists_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_class
    controller.controller_path.split('/').join('_') + " " + action_name
  end

  def bootstrap_class_for(flash_type)
    { success: "alert-success", error: "alert-danger",
      alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |flash_type, message|
      concat(
        content_tag(:div, message, class: "alert alert-dismissable #{bootstrap_class_for(flash_type)} fade in") do
          concat(
            content_tag(:button, class: "close", data: { dismiss: "alert" }) do
              concat content_tag(:span, "&times;".html_safe)
            end
          )
          concat message
        end
      )
    end
  end

  def flash_messages?
    if flash.present?
      true
    else
      false
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-125800376-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-125800376-1');
    </script>
    <title>AIS-LOG</title>
    <meta name="description" content="AIS -All Idol Songs-の情報をまとめている非公式サイトです">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': false %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': false %>
  </head>

  <body class="<%= body_class %>">
    <% if flash_messages? %>
    <div class="container-fluid">
      <% flash_messages %>
    </div>
    <% end %>
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <div class="container">
        <%= link_to 'AIS-LOG', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#header-menu" aria-controls="header-menu" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="header-menu">
          <ul class="navbar-nav ml-auto justify-content-end">
            <li class="nav-item">
              <%= link_to 'ライブ', setlists_path %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/media/_youtube.html.erb
<li class="clearfix youtube">
  <%= link_to "https://www.youtube.com/watch?v=#{y.video_id}" do %>
    <div class="image pull-left">
      <img src="http://i.ytimg.com/vi/<%= y.video_id %>/maxresdefault.jpg" alt="">
    </div>
    <div class="description pull-left">
      <%= y.title %>
      <%= y.playtime %>
      <%= y.published_at %>
      <div class="tags">
        <% y&.medium&.tags.each do |t| %>
          <%= link_to tag_path(t) do %>
            <span><%= t.name %></span>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</li>

app/views/lives/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ul>
        <% @lives.each do |l| %>
          <li>
            <%= l.held_at %> / <%= l.title %> / <%= l.place %> / <%= l.description %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/music_lists/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ul>
        <% @music_lists.each do |m| %>
          <li>
            <%= link_to music_list_path(m) do %>
              <%= m.name %> - <%= m.artist %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/music_lists/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <ul>
        <li><%= @music.name %> - <%= @music.artist %></li>
      </ul>
    </div>
    <div class="col-md-12 media">
      <h3>AIS動画</h3>
      <ul>
      <% @music.youtubes.each do |y| %>
        <%= render 'layouts/media/youtube', y: y %>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/setlists/index.html.erb
<div class="col-md-12">
  <h2 class="py-3">ライブ</h2>
</div>

<div class="col-md-12">
  <% @setlists.each do |date, s| %>
    <div class="setlist">
      <div class="date pt-3">
        <%= date.strftime("%Y/%m/%d") %>
      </div>
      <% s.each do |setlist| %>
        <%= link_to setlist_path(setlist) do %>
          <div class="title pl-3 py-2">
            <%= setlist.title %> @<%= setlist.place %> / OPEN: <%= setlist.event_date.strftime("%H:%M") %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/setlists/show.html.erb
<div class="col-md-12">
  <div class="top py-3">
    <h2 class="pb-3">ライブ</h2>
    <h4><%= @setlist.title %> @<%= @setlist.place %></h4>
    <% if @setlist.description.present? %>
      <div class="description py-2"><%= @setlist.description %></div>
    <% end %>
    <div class="date"><%= @setlist.event_date.strftime("%Y/%m/%d %H:%M") %></div>
  </div>
</div>

<div class="col-md-12 pt-3 setlist">
  <ul>
    <% @setlist.setlist_details.each do |sd| %>
      <li class="mb-3 pb-3">
        <div class="title">
          <% if sd.music_order.present? %>
            <span><%= format("%02d", sd.music_order) %></span>
          <% end %>
          <%= sd.title %>
        </div>
        <% if sd.description.present? %>
          <div class="description pl-2">
            <%= sd.description %>
          </div>
        <% end %>

        <% if sd.youtube.present? %>
          <%= link_to "https://www.youtube.com/watch?v=#{sd.youtube}", class: 'btn btn-danger my-2', target: '_blank' do %>
            <%= fa_icon "youtube", type: :fab %> Youtube
          <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/tags/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 media">
      <h3>Tag: <%= @tag.name %></h3>
      <ul>
      <% @media.each do |m| %>
        <% case %>
        <% when m.youtube? %>
          <%= render 'layouts/media/youtube', y: m.youtube %>
        <% end %>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/admins/index.html.erb
<h1>Success!!</h1>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="official-movie">
        <h3>公式動画</h3>
        <%= @m.name %>
        <% if @m.content.present? %>
          <img src="http://i.ytimg.com/vi/irsEhYKgGM8/maxresdefault.jpg" width="400px">
        <% else %>
        <p>
          <%= link_to 'Youtubeで見る', 'https://www.youtube.com/results?search_query=m.name' %>
        </p>
        <% end %>
      </div>
      <div class="ais-movies">
        <h3>AIS動画</h3>
        <ul>
          <% @m.ais_lists.each do |a| %>
            <li>
              <h4><%= a.title %></h4>
              <img src="http://i.ytimg.com/vi/<%= a.content %>/maxresdefault.jpg" width="400px">
              <p>公開日時: 2018-06-20</p>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>